tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline-variant": "#bfcaba",
                "primary-fixed-dim": "#88d982",
                "on-error-container": "#93000a",
                "outline": "#707a6c",
                "on-primary-fixed": "#002204",
                "on-secondary": "#ffffff",
                "surface-variant": "#e2e2e2",
                "secondary-fixed-dim": "#add0a6",
                "on-secondary-container": "#4c6a48",
                "surface-container-low": "#f3f3f3",
                "on-primary-container": "#cbffc2",
                "tertiary-fixed": "#ffd9e2",
                "surface-container-high": "#e8e8e8",
                "secondary": "#476644",
                "on-primary-fixed-variant": "#005312",
                "on-secondary-fixed-variant": "#304e2e",
                "inverse-surface": "#2f3131",
                "surface-container": "#eeeeee",
                "surface-tint": "#1b6d24",
                "error": "#ba1a1a",
                "on-tertiary-fixed-variant": "#7f2448",
                "on-surface-variant": "#40493d",
                "on-primary": "#ffffff",
                "background": "#f9f9f9",
                "on-tertiary-container": "#ffedf0",
                "inverse-primary": "#88d982",
                "tertiary": "#923357",
                "on-background": "#1a1c1c",
                "error-container": "#ffdad6",
                "on-surface": "#1a1c1c",
                "on-tertiary": "#ffffff",
                "secondary-fixed": "#c9ecc1",
                "surface-container-lowest": "#ffffff",
                "primary-fixed": "#a3f69c",
                "on-secondary-fixed": "#052106",
                "primary-container": "#2e7d32",
                "tertiary-fixed-dim": "#ffb1c7",
                "primary": "#0d631b",
                "on-tertiary-fixed": "#3f001c",
                "surface-bright": "#f9f9f9",
                "inverse-on-surface": "#f1f1f1",
                "surface-container-highest": "#e2e2e2",
                "tertiary-container": "#b14b6f",
                "secondary-container": "#c6e9be",
                "surface-dim": "#dadada",
                "on-error": "#ffffff",
                "surface": "#f9f9f9"
            },
            fontFamily: {
                "headline": ["Public Sans"],
                "body": ["Public Sans"],
                "label": ["Public Sans"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
}