tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#005312",
        "on-primary": "#ffffff",
        "surface-tint": "#1b6d24",
        "secondary-fixed": "#c9ecc1",
        "on-tertiary-fixed": "#3f001c",
        "tertiary": "#923357",
        "on-secondary-container": "#4c6a48",
        "on-primary-container": "#cbffc2",
        "on-error": "#ffffff",
        "surface-container": "#eeeeee",
        "primary-container": "#2e7d32",
        "secondary-container": "#c6e9be",
        "on-background": "#1a1c1c",
        "inverse-primary": "#88d982",
        "surface-container-high": "#e8e8e8",
        "surface-bright": "#f9f9f9",
        "on-surface-variant": "#40493d",
        "primary-fixed": "#a3f69c",
        "primary": "#0d631b",
        "error": "#ba1a1a",
        "on-primary-fixed": "#002204",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3131",
        "secondary": "#476644",
        "on-surface": "#1a1c1c",
        "outline-variant": "#bfcaba",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "tertiary-container": "#b14b6f",
        "tertiary-fixed": "#ffd9e2",
        "on-secondary-fixed-variant": "#304e2e",
        "on-secondary-fixed": "#052106",
        "on-tertiary-fixed-variant": "#7f2448",
        "surface-dim": "#dadada",
        "outline": "#707a6c",
        "secondary-fixed-dim": "#add0a6",
        "primary-fixed-dim": "#88d982",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "tertiary-fixed-dim": "#ffb1c7",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-container": "#ffedf0",
        "surface": "#f9f9f9"
      },
      fontFamily: {
        "headline": ["Public Sans"],
        "body": ["Public Sans"],
        "label": ["Public Sans"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
}